    const wardrobe={topwear:[['rainbow','Rainbow tee','🌈'],['jacket','Cool jacket','🧥'],['pink','Pink top','💗']],costume:[['unicorn','Unicorn costume','🦄'],['fairy','Fairy costume','🧚'],['hero','Superhero costume','🦸']],hat:[['top','Top hat','🎩'],['crown','Crown','👑'],['cap','Cap','🧢']],glasses:[['cool','Cool shades','😎'],['funny','Funny glasses','🤓'],['silly','Silly glasses','🤪']],hand:[['bag','Handbag','👜'],['balloon','Balloon','🎈'],['wand','Magic wand','🪄']]};
    const state={bear:'bubble',bg:'candy',pose:'bounce',topwear:'',costume:'',hat:'',glasses:'',hand:''};let active='topwear';
    const items=document.querySelector('#items'),say=document.querySelector('#compliment'),nice=['So stylish!','Wow, sparkly!','Super cute!','Ta-da!','Amazing choice!'];
    const scene=document.querySelector('#scene'),bear=document.querySelector('#bear'),bearWrap=document.querySelector('#bearWrap'),clearBtn=document.querySelector('#clear'),poseBtn=document.querySelector('#pose'),surpriseBtn=document.querySelector('#surprise'),doneBtn=document.querySelector('#done'),finishBtn=document.querySelector('#finish'),modal=document.querySelector('#modal'),again=document.querySelector('#again'),photoBear=document.querySelector('#photoBear'),photoScene=document.querySelector('#photoScene');
    const cheer=()=>{say.textContent=nice[Math.floor(Math.random()*nice.length)];say.animate([{transform:'scale(.7)'},{transform:'scale(1.1)'},{transform:'scale(1)'}],{duration:350})};
    const spark=()=>{let s=document.createElement('span');s.className='burst';s.textContent='✨ 💖 ⭐';scene.append(s);setTimeout(()=>s.remove(),700)};
    function layers(changedCategory=''){for(const k of Object.keys(wardrobe)){let el=document.querySelector('#'+k);el.className='layer '+k+(state[k]?' '+k+'-'+state[k]:' empty');el.setAttribute('aria-label',state[k]||'');if(k===changedCategory&&state[k]){el.classList.remove('changed');void el.offsetWidth;el.classList.add('changed')}}}
    function wear(category,icon){if(category==='costume')state.topwear='';if(category==='topwear')state.costume='';state[category]=icon;layers(category);render();spark();cheer()}
    function render(){items.innerHTML='';if(active==='clear-one'){Object.keys(wardrobe).forEach(k=>add('🧼','Clear '+k,()=>{state[k]='';layers();render();cheer()}));return}wardrobe[active].forEach(([id,name,icon])=>add(icon,name,()=>wear(active,id),state[active]===id,active,id))}
    let pointerDrag=null;
    function add(icon,name,fn,selected=false,category='',id=''){let b=document.createElement('button');b.className='option'+(selected?' selected':'');b.innerHTML=icon+'<span>'+name+'</span>';b.setAttribute('aria-label',name);b.draggable=Boolean(category);b.onclick=fn;if(category){b.dataset.category=category;b.dataset.item=id;b.addEventListener('dragstart',event=>{event.dataTransfer.setData('text/plain',JSON.stringify({category,item:id}));event.dataTransfer.effectAllowed='copy';b.classList.add('dragging')});b.addEventListener('dragend',()=>b.classList.remove('dragging'));b.addEventListener('pointerdown',event=>{if(event.button!==0)return;const ghost=document.createElement('div');ghost.className='drag-ghost';ghost.textContent=icon;ghost.style.left=event.clientX+'px';ghost.style.top=event.clientY+'px';document.body.append(ghost);pointerDrag={category,item:id,ghost,moved:false}})}items.append(b)}
    document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{active=b.dataset.cat;document.querySelectorAll('.tab').forEach(x=>x.setAttribute('aria-selected',x===b));render()});
    document.querySelectorAll('#bears button').forEach(b=>b.onclick=()=>{state.bear=b.dataset.bear;bear.dataset.bear=state.bear;document.querySelectorAll('#bears button').forEach(x=>x.classList.toggle('selected',x===b));spark();cheer()});
    document.querySelectorAll('#backgrounds button').forEach(b=>b.onclick=()=>{state.bg=b.dataset.bg;scene.dataset.bg=state.bg;document.querySelectorAll('#backgrounds button').forEach(x=>x.classList.toggle('selected',x===b));cheer()});
    scene.addEventListener('dragover',event=>{event.preventDefault();event.dataTransfer.dropEffect='copy';scene.classList.add('drag-over')});scene.addEventListener('dragleave',event=>{if(!scene.contains(event.relatedTarget))scene.classList.remove('drag-over')});scene.addEventListener('drop',event=>{event.preventDefault();scene.classList.remove('drag-over');try{const {category,item}=JSON.parse(event.dataTransfer.getData('text/plain'));if(wardrobe[category]?.some(choice=>choice[0]===item))wear(category,item)}catch{say.textContent='Try a closet item!'}});
    document.addEventListener('pointermove',event=>{if(!pointerDrag)return;pointerDrag.moved=true;pointerDrag.ghost.style.left=event.clientX+'px';pointerDrag.ghost.style.top=event.clientY+'px';const box=scene.getBoundingClientRect();scene.classList.toggle('drag-over',event.clientX>=box.left&&event.clientX<=box.right&&event.clientY>=box.top&&event.clientY<=box.bottom)});document.addEventListener('pointerup',event=>{if(!pointerDrag)return;const {category,item,ghost,moved}=pointerDrag,box=scene.getBoundingClientRect(),inside=event.clientX>=box.left&&event.clientX<=box.right&&event.clientY>=box.top&&event.clientY<=box.bottom;ghost.remove();pointerDrag=null;scene.classList.remove('drag-over');if(moved&&inside)wear(category,item)});
    clearBtn.onclick=()=>{Object.keys(wardrobe).forEach(k=>state[k]='');layers();render();say.textContent='Fresh and ready!'};poseBtn.onclick=()=>{const poses=['bounce','wave','twirl'];state.pose=poses[(poses.indexOf(state.pose)+1)%poses.length];bearWrap.dataset.pose=state.pose;say.textContent='Look at that pose!'};surpriseBtn.onclick=()=>{const outfitType=Math.random()>.5?'topwear':'costume';state[outfitType]=wardrobe[outfitType][Math.floor(Math.random()*wardrobe[outfitType].length)][0];state[outfitType==='topwear'?'costume':'topwear']='';['hat','glasses','hand'].forEach(k=>state[k]=wardrobe[k][Math.floor(Math.random()*wardrobe[k].length)][0]);layers(outfitType);render();spark();say.textContent='Surprise! What a look!'};
    function finish(){let copy=bearWrap.cloneNode(true);copy.removeAttribute('id');photoBear.replaceChildren(copy);photoScene.dataset.bg=state.bg;modal.classList.add('show');again.focus()}doneBtn.onclick=finish;finishBtn.onclick=finish;again.onclick=()=>{modal.classList.remove('show');finishBtn.focus()};
    render();

